CREATE TABLE cxs.td_cxs_real (
   Mes VARCHAR(10),
                    Sector VARCHAR(20),
                    Canal VARCHAR(60),
                    Subcanal VARCHAR(60),
                    Canal_Trans VARCHAR(60),
                    Subcanal_Trans VARCHAR(60),
                    Oficina_ventas VARCHAR(20),
                    Formato_NIF VARCHAR(60),
                    Formato VARCHAR(60),
                    Segmento_Agrup VARCHAR(60),
                    Centro_Costo VARCHAR(20),
                    Nombre_Centro_Costo VARCHAR(60),
                    Ventas_Efectivas DECIMAL(18,5),
                    Descuentos DECIMAL(18,5),
                    Gasto_Prom_Comercializadores DECIMAL(18,5),
                    Descuentos_NG DECIMAL(18,5),
                    Total_Gastos_CN DECIMAL(18,5),
                    Depuracion_Dctos DECIMAL(18,5),
                    Dctos_Grupo DECIMAL(18,5),
                    Ventas_Efectivas_Grupo DECIMAL(18,5),
                    Descuentos_CN DECIMAL(18,5),
                    Ventas_Netas_CN DECIMAL(18,5),
                    Ventas_Netas_Grupo DECIMAL(18,5),
                    Cliente VARCHAR(100),
                    Oficina_ventas_Agrup VARCHAR(20),
                    Devoluciones_malas DECIMAL(18,5),
                    Ventas_Efectivas_Final DECIMAL(18,5),
                    Tipo VARCHAR(11)
);



CREATE TABLE cxs.td_cxs_ppto_estatico (
   Mes VARCHAR(10),
                    Sector VARCHAR(20),
                    Canal VARCHAR(60),
                    Subcanal VARCHAR(60),
                    Canal_Trans VARCHAR(60),
                    Subcanal_Trans VARCHAR(60),
                    Oficina_ventas VARCHAR(20),
                    Formato_NIF VARCHAR(60),
                    Formato VARCHAR(60),
                    Segmento_Agrup VARCHAR(60),
                    Centro_Costo VARCHAR(20),
                    Nombre_Centro_Costo VARCHAR(60),
                    Ventas_Efectivas DECIMAL(18,5),
                    Descuentos DECIMAL(18,5),
                    Gasto_Prom_Comercializadores DECIMAL(18,5),
                    Descuentos_NG DECIMAL(18,5),
                    Total_Gastos_CN DECIMAL(18,5),
                    Depuracion_Dctos DECIMAL(18,5),
                    Dctos_Grupo DECIMAL(18,5),
                    Ventas_Efectivas_Grupo DECIMAL(18,5),
                    Descuentos_CN DECIMAL(18,5),
                    Ventas_Netas_CN DECIMAL(18,5),
                    Ventas_Netas_Grupo DECIMAL(18,5),
                    Cliente VARCHAR(100),
                    Oficina_ventas_Agrup VARCHAR(20),
                    Devoluciones_malas DECIMAL(18,5),
                    Ventas_Efectivas_Final DECIMAL(18,5),
                    Tipo VARCHAR(11)
);